import { LEGAL_BUSINESS, LEGAL_EFFECTIVE_DATE, LEGAL_VERSION } from "@/lib/legal-version";
import { REFUND_RESPONSE_BUSINESS_DAYS, REFUND_RSVP_LIMIT, REFUND_WINDOW_DAYS, SERVICE_FAILURE_FIX_HOURS } from "@/lib/payments/refund-policy";

export { LEGAL_BUSINESS, LEGAL_EFFECTIVE_DATE, LEGAL_VERSION } from "@/lib/legal-version";

// Plain-language drafts written to match how the product works on LEGAL_VERSION. They have NOT been
// reviewed by a lawyer; docs/legal/OWNER-REVIEW.md lists the decisions that need confirmation.
//
// Section bodies: paragraphs are separated by a blank line; a paragraph whose lines all start with "- " is a list.
// Each document is hashed (legalDocumentCanonicalText → SHA-256) into legal_documents.content_sha256 by the
// migration for its version. Editing any text, or any constant interpolated below, changes the hash and
// fails src/lib/tests/legal-documents.test.ts until LEGAL_VERSION is bumped and a new migration is written.

export type LegalSection = { heading: string; body: string };
export type LegalDocument = { slug: string; title: string; summary: string; sections: LegalSection[] };

/** Retention constants that mirror the database. Tests check them against the migrations. */
export const RSVP_RETENTION_DAYS_AFTER_EVENT = 90;
export const RATE_LIMIT_RETENTION_DAYS = 30;
export const HOSTING_TERM_MONTHS = 12;
export const LAUNCH_PRICE_USD = 20;

const { name, email, mailingAddress } = LEGAL_BUSINESS;
const contact = `${name}, ${mailingAddress}. Email: ${email}.`;
const price = `US$${LAUNCH_PRICE_USD}`;

export const legalDocuments: LegalDocument[] = [
  { slug: "terms", title: "Terms of Service", summary: "The agreement between you and Eventloom when you create an account or publish an event page.", sections: [
    { heading: "Who we are and what these Terms cover", body: `${name} ("Eventloom", "we", "us") is an online service, run from ${LEGAL_BUSINESS.jurisdiction}, for creating event web pages and collecting RSVPs. These Terms are the agreement between us and you when you create an Eventloom account or use Eventloom to build or publish an event page ("you", "host").\n\nThese Terms include our Acceptable Use Policy, Refund and Cancellation Policy, Content Reporting and Enforcement policy, and Copyright and Takedown policy. Our Privacy Policy explains how we handle personal information. Guests who only view a page or send an RSVP are not bound by these Terms, but the Acceptable Use Policy applies to everyone.\n\nContact: ${contact}` },
    { heading: "Who can use Eventloom", body: "You must be at least 18 years old and able to enter a binding contract. If you use Eventloom for an organization, you confirm you are allowed to accept these Terms for it.\n\nGive accurate account information, keep your password and sign-in methods secure, and tell us promptly if you think someone else has used your account. You are responsible for activity under your account." },
    { heading: "What you get and what it costs", body: `- Building and editing draft pages is free. New accounts get a starter AI credit for generating and editing pages with AI. AI credit has no cash value, can't be transferred or exchanged for money, and we may change how much is included.\n- Publishing an event page costs ${price}, paid once per event. It includes ${HOSTING_TERM_MONTHS} months of hosting for that page from the date of payment, RSVP collection, the guest dashboard and continued editing. A bonus AI credit is added when you publish.\n- There is no subscription and nothing renews automatically. Renewal is not offered yet: when the ${HOSTING_TERM_MONTHS} months end, the page stops being publicly available. We won't charge you again without your new purchase.\n- Prices are in US dollars. If we are required to charge sales tax, we will show it before you pay. Your bank may add currency-conversion fees.\n- Payments are processed by Stripe. Eventloom never sees or stores your full card number.\n- Custom-domain purchase is not currently offered. Our Domain Registration Policy applies only if and when we offer it.\n- Refunds are covered by our Refund and Cancellation Policy.` },
    { heading: "Your content", body: "You keep ownership of everything you add to Eventloom: text, photos, event details and your RSVP questions (\"your content\"). You give us a non-exclusive, worldwide, royalty-free licence to host, store, copy, display, resize and adapt your content, and to send it to our service providers, only as needed to run Eventloom for you, keep it secure and enforce these Terms. The licence ends when you delete the content or your account, except for copies kept in backups for a limited time or where the law requires us to keep them.\n\nYou confirm that you have the rights and permissions needed for your content, including permission from people who appear in your photos." },
    { heading: "AI-generated content", body: "Eventloom uses AI (currently OpenAI) to draft and edit pages from what you tell it. AI output can be wrong, incomplete or made up: it may invent or change dates, times, addresses, names, prices, menus, dress codes or other details, and it may resemble content that already exists.\n\nYou must review everything on your page before you publish it and whenever you change it. You are responsible for the accuracy of everything on your page, whether you wrote it or the AI did, and for what you tell your guests. Do not rely on AI-generated text for safety, medical, allergy, legal or accessibility information without checking it yourself. We don't promise that AI output is unique, error-free or free of other people's rights." },
    { heading: "Your responsibilities as a host", body: "- Follow the Acceptable Use Policy and the law, including privacy and anti-spam laws.\n- Before publishing, fill in your event's privacy notice (who is collecting replies, how guests can contact you, and why you are collecting the information). Ask guests only for information you actually need for the event.\n- Use guest replies only for your event. Don't sell them or add guests to marketing lists. Eventloom does not send messages to your guests; if you contact guests yourself, you are responsible for following anti-spam laws such as Canada's Anti-Spam Legislation (CASL).\n- Help your guests if they ask to see, correct or delete their reply.\n- You, not Eventloom, are responsible for your event itself: the venue, safety, tickets, gifts, money you collect outside Eventloom, and anything else you arrange with guests." },
    { heading: "Moderation, reports and enforcement", body: "We use automated checks (including OpenAI's moderation service) on event text and uploaded images, and anyone can report a page using \"Report this page\" or by email. We review reports and may remove content, block publishing, suspend a page (take it offline and close RSVPs), or suspend or close an account when we reasonably believe the Acceptable Use Policy or these Terms have been broken, when the law requires it, or to protect people or the service. Where the law requires, we preserve information and report it to the authorities, including reports of child sexual abuse material.\n\nWe will normally tell you what we did and why, and you can appeal. Our Content Reporting and Enforcement policy explains the process. Pages suspended or removed for breaking our rules are not refunded." },
    { heading: "Ending your use of Eventloom", body: "You can stop using Eventloom at any time and can delete events or your account from your dashboard. Deleting an event or account does not by itself give you a refund; see the Refund and Cancellation Policy.\n\nWe may close your account for serious or repeated breaches of these Terms. If we decide to stop offering Eventloom altogether, we will give at least 30 days' notice where we can and refund the unused part of the hosting period you paid for." },
    { heading: "Availability and changes to the service", body: "We work to keep Eventloom running and secure, but we don't guarantee it will always be available, uninterrupted or error-free. We may need to pause it for maintenance, security or reasons outside our control, and we may change or remove features. If a fault on our side stops your published page from working, the Refund and Cancellation Policy explains your options." },
    { heading: "Disclaimers", body: "To the extent the law allows, Eventloom is provided \"as is\" and \"as available\", without promises that it will meet your particular needs. We are not a party to anything between hosts and guests and are not responsible for events, attendance, or what hosts or guests do.\n\nSome laws, including consumer protection laws where you live, give you rights that cannot be excluded. Nothing in these Terms takes those rights away." },
    { heading: "Limitation of liability", body: `To the extent the law allows, Eventloom is not liable for indirect, incidental, special or consequential losses, lost profits, lost data, or costs of your event (such as venue, catering or travel), even if we were told they were possible. Our total liability for all claims relating to Eventloom is limited to the greater of the amount you paid us in the 12 months before the claim arose and US$100.\n\nThese limits don't apply to liability that cannot legally be limited, such as liability for fraud, wilful misconduct, gross negligence, or death or personal injury caused by negligence.` },
    { heading: "Responsibility for your content", body: "To the extent the law allows, you agree to cover reasonable costs and losses Eventloom suffers because of a claim by someone else that arises from your content, your event, or your breach of these Terms." },
    { heading: "Governing law and disputes", body: `These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada that apply there. The courts of Ontario have jurisdiction over disputes about these Terms or Eventloom.\n\nIf you are a consumer living elsewhere, you keep the protection of the mandatory laws of the place you live and may be able to bring a claim in your local courts. There is no arbitration clause and no class-action waiver in these Terms.\n\nPlease contact us first at ${email}; we will try to resolve any problem informally within 30 days.` },
    { heading: "Changes to these Terms", body: `Each version of these Terms has a version number and effective date (this version: ${LEGAL_VERSION}, effective ${LEGAL_EFFECTIVE_DATE}). When we make material changes we will publish the new version here and ask you to accept it the next time you sign in to Eventloom, and before you publish another page. If you don't agree, you can stop using Eventloom. Changes don't shorten hosting you have already paid for.` },
    { heading: "Other terms", body: "These Terms and the policies they include are the whole agreement between you and us about Eventloom. If a court finds part of them unenforceable, the rest still applies. If we don't enforce a right straight away, we haven't given it up. You may not transfer these Terms to someone else without our written consent; we may transfer them as part of a sale or reorganization of the business, and the new owner must honour them." },
    { heading: "Contact", body: contact },
  ]},
  { slug: "privacy", title: "Privacy Policy", summary: "What personal information Eventloom collects about hosts, guests and visitors, why, who we share it with, how long we keep it, and your rights.", sections: [
    { heading: "Who is responsible", body: `${name} is responsible for the personal information it collects to run the service: host accounts, billing, security, support and reports. ${name} is based in ${LEGAL_BUSINESS.jurisdiction}; our privacy contact is ${email}.\n\nRSVP replies are different. The host of each event decides what to ask guests and why, so the host is responsible for guest replies (the "controller"). Eventloom stores and processes replies for the host (as a "processor" or "service provider") under our Creator Data Processing Addendum. Each event's RSVP form shows the host's own privacy contact.` },
    { heading: "Information we collect about hosts", body: "- Account: email address, name, password (stored only as a secure hash by our authentication provider; we never see it), Google sign-in identifiers if you sign in with Google, multi-factor authentication settings, your 18+ confirmation, and records of which policy versions you accepted (version, time, a keyed hash of your IP address and your browser type).\n- Event content: what you tell the page builder, page text, schedule, location, RSVP questions, your event privacy notice, version history, and photos you upload. We resize uploaded photos and remove their hidden metadata, such as GPS location.\n- AI use: the instructions you give the AI and a record of AI credit granted and used.\n- Payments: order and payment records (amount, currency, date, status and Stripe reference numbers). Stripe collects your card and billing details; we never receive your full card number.\n- Support, feedback and requests: messages you send us, product feedback, and privacy requests (stored encrypted)." },
    { heading: "Information we collect about guests", body: "When a guest replies to an event, the host receives:\n\n- name, whether they are attending, and party size;\n- names of other people in their party;\n- email address and phone number, only if the host asks for them;\n- meal choices or dietary notes, answers to the host's own questions, and any note to the host.\n\nDietary notes can reveal health or religious information; share only what you are comfortable sharing. To stop spam we also keep a keyed hash of the IP address (not the address itself) with each reply attempt, and the RSVP form runs a Cloudflare Turnstile bot check. We do not send guest replies to OpenAI." },
    { heading: "Information about everyone who visits", body: "- Technical and security data: our hosting provider (Vercel) processes IP addresses, browser details and the pages requested in order to deliver pages and protect the service. Where we keep IP information in our own database (rate limits, abuse logs, reports, policy acceptance) we store a keyed hash, not the address.\n- Content reports: what you report, why, any details you add, your email address if you choose to give it, and a keyed hash of your IP address.\n- We do not use analytics, advertising cookies, tracking pixels or cross-site tracking. Event pages ask search engines not to index them." },
    { heading: "How we use information", body: "- To provide Eventloom: accounts, building and hosting pages, collecting RSVPs, showing replies to the host, exports and deletion.\n- To run AI features: we send your instructions, page text and photos you choose to use to OpenAI to generate or edit your page.\n- To keep Eventloom safe: automated moderation of event text and uploaded images (OpenAI), bot checks (Cloudflare Turnstile), rate limiting, reviewing reports, suspending pages that break our rules, and investigating misuse.\n- To take payments and keep tax and accounting records.\n- To answer support, privacy and legal requests, and to meet legal obligations.\n- To improve Eventloom using feedback you send us.\n\nWe do not sell personal information, use guest replies for our own marketing, show advertising, or use your content or guest replies to train AI models. Our AI provider's API terms say API data is not used to train its models by default.\n\nWe send account emails (such as sign-in links and password resets). We don't send marketing emails unless you have agreed to receive them, and every marketing email will have an unsubscribe link." },
    { heading: "Legal bases (EU and UK)", body: "If EU or UK data protection law applies to you, we rely on: performing our contract with you (providing the service); our legitimate interests in keeping the service secure, preventing abuse and improving it; legal obligations (such as tax records and lawful requests); and consent where we ask for it. For guest replies, the host decides the legal basis." },
    { heading: "Who we share information with", body: "- The host: guest replies are shared with the host of that event, who can view and export them.\n- Service providers that run parts of Eventloom for us, under contracts that limit how they use the information: Supabase (authentication, database and photo storage), Vercel (hosting and delivery), OpenAI (AI generation and content moderation), Stripe (payments), Cloudflare (Turnstile bot checks) and ImprovMX (forwarding email sent to our addresses). Our Subprocessors page has details.\n- Authorities or others when the law requires it, or when needed to protect someone's safety, investigate fraud or abuse, or enforce our Terms.\n- A buyer or successor if the business is sold or reorganized, who must keep protecting the information as this policy describes.\n\nFonts on Eventloom pages are served from our own domain, so loading a page does not send your information to Google." },
    { heading: "Where information is stored", body: "Eventloom is based in Canada, but our providers store and process information in the United States and other countries (for example, our database is hosted in the United States and Vercel and Cloudflare operate worldwide). Information stored abroad is subject to the laws of those countries and may be accessible to their courts and authorities. We rely on our providers' contractual safeguards, such as standard contractual clauses, for transfers from the EU and UK." },
    { heading: "How long we keep information", body: `- Guest replies: automatically deleted ${RSVP_RETENTION_DAYS_AFTER_EVENT} days after the event's end date, by a daily job, unless a legal hold applies. They are deleted sooner if the host deletes the reply, the event or their account.\n- Hashed IP records used for RSVP rate limits: deleted after ${RATE_LIMIT_RETENTION_DAYS} days. The hashed IP on product feedback is removed after ${RATE_LIMIT_RETENTION_DAYS} days.\n- Event pages, drafts and photos: kept until you delete the event or your account. A published page goes offline when its paid hosting ends; the draft stays in your dashboard until you delete it.\n- Your account: kept until you delete it. When you delete your account we delete your events, photos and guest replies. We keep order, payment and policy-acceptance records, separated from your account, for as long as tax and accounting law requires (generally six years after the end of the tax year in Canada).\n- Security and audit logs: kept up to 12 months unless needed for an ongoing investigation.\n- Content reports and enforcement records: kept as long as needed to handle the report, prevent repeat abuse and meet legal obligations.\n- Privacy requests: kept as long as needed to show how we handled them.\n- Backups: deleted information can remain in our providers' backups for a limited time until it is overwritten.` },
    { heading: "Your rights and how to make a request", body: `Depending on where you live, you can ask to access, correct or delete your personal information, withdraw consent, or (in the EU and UK) object to or restrict processing and receive your data in a portable format. Making a request is free.\n\n- Hosts: you can export guest replies, delete events and delete your account from your dashboard, or use the privacy request form.\n- Guests: the quickest route is the host, whose privacy contact is shown on the RSVP form. You can also use our privacy request form at /privacy/request. Because the host is responsible for replies, we may pass your request to them, and we will help them answer it.\n\nWe verify your identity before showing or changing information and aim to reply within 30 days, as Canadian law requires (we will tell you if we need an extension the law allows). You can also complain to the Office of the Privacy Commissioner of Canada or, in the EU or UK, your local data protection authority.` },
    { heading: "Children", body: "Hosts must be at least 18, and Eventloom is not directed at children. Guest replies may include the names of children attending an event, entered by a parent, guardian or the host; hosts should ask only for what they need. If you believe a child has given us personal information without a parent's or guardian's consent, contact us and we will delete it." },
    { heading: "Security", body: "We use HTTPS everywhere, encryption at rest by our providers, access controls that keep each host's data separate, extra verification (multi-factor authentication) for sensitive actions such as paying, exporting guest data and deleting an account, keyed hashing of IP addresses, private photo storage with metadata removed, encrypted privacy requests and signed payment notifications. No system is perfectly secure. If a breach creates a real risk of significant harm, we will notify affected people and the Privacy Commissioner of Canada as the law requires, and other regulators where their laws apply." },
    { heading: "Changes and contact", body: `We will post changes here with a new version number and effective date (this version: ${LEGAL_VERSION}, effective ${LEGAL_EFFECTIVE_DATE}) and ask hosts to accept material changes the next time they sign in. Questions or complaints: ${contact}` },
  ]},
  { slug: "refunds", title: "Refund and Cancellation Policy", summary: `When the one-time ${price} launch fee can be refunded, how to ask, and what happens to your page.`, sections: [
    { heading: "Summary", body: `- Publishing an event page costs ${price}, once, for ${HOSTING_TERM_MONTHS} months of hosting. There is no subscription and nothing renews automatically, so there is nothing to cancel.\n- Full refund within ${REFUND_WINDOW_DAYS} days of payment if fewer than ${REFUND_RSVP_LIMIT} RSVPs have been received and your event hasn't ended.\n- Full refund at any time before your event ends if a fault on our side breaks your page and we can't fix it within ${SERVICE_FAILURE_FIX_HOURS} hours.\n- No refunds after your event has ended.\n- Ask by email to ${email}.` },
    { heading: "When you can get a full refund", body: `- Change of mind: you ask within ${REFUND_WINDOW_DAYS} days of the date you paid, your page has received fewer than ${REFUND_RSVP_LIMIT} RSVPs (each submitted RSVP form counts once, whatever the party size, including test replies you sent yourself), and your event has not yet ended (the end date and time you set in Eventloom).\n- Our fault: your published page can't be reached, or guests can't send RSVPs, because of a problem on our side that we don't fix within ${SERVICE_FAILURE_FIX_HOURS} hours of you telling us. This applies at any time before your event ends, however many RSVPs you have.\n- Charged by mistake: if you were charged twice or charged in error, we refund the extra charge.\n- If we stop offering Eventloom, we refund the unused part of your hosting period.` },
    { heading: "When refunds are not available", body: `- After ${REFUND_WINDOW_DAYS} days, or once your page has received ${REFUND_RSVP_LIMIT} or more RSVPs, unless the problem is our fault or a mistaken charge.\n- After your event has ended.\n- If your page was suspended or removed for breaking our Terms or Acceptable Use Policy.\n- If your event is cancelled or postponed. You can keep editing your page to tell guests about the change, and the change-of-mind refund still applies if you meet its conditions.\n- For unused time left in the ${HOSTING_TERM_MONTHS}-month hosting period.\n- For AI credit (the free starter credit or the bonus added when you publish), which has no cash value.` },
    { heading: "How to ask for a refund", body: `Email ${email} from the email address on your Eventloom account. Include the address (link) of your event page and a short reason. Please ask before deleting the event: deleting an event does not refund it, and once it is deleted we can't check that it qualifies.\n\nWe reply within ${REFUND_RESPONSE_BUSINESS_DAYS} business days. Refunds under this policy are always full refunds of the launch fee and we charge no fee for them.` },
    { heading: "What happens after a refund", body: `- The refund goes back to the payment method you used, through Stripe. Banks usually take 5 to 10 business days to show it.\n- Your page is unpublished as soon as the refund is processed: guests can no longer see it and RSVPs close.\n- Your draft and any replies already received stay in your dashboard until they are deleted on the normal schedule (guest replies are deleted ${RSVP_RETENTION_DAYS_AFTER_EVENT} days after the event ends).\n- A refunded event can't be published again. If you change your mind, create a new event and publish that one.` },
    { heading: "Chargebacks", body: "Please contact us before disputing a charge with your bank; it is usually faster. If you open a dispute, we may unpublish the page while it is open. If the dispute is decided in your favour, the page is treated as refunded and stays unpublished. If the page was used for your event, we will give Stripe evidence of that. We may close accounts that file chargebacks in bad faith." },
    { heading: "Your legal rights", body: "This policy does not limit any right to cancel or get a refund that you have under consumer protection law where you live, such as Ontario's consumer protection laws or the EU right of withdrawal. If the law gives you more, we will honour it." },
    { heading: "Custom domains", body: "Custom-domain purchase is not currently offered, so no domain charges apply. If we offer it in future, this policy will be updated to cover domain fees before anyone can buy one." },
    { heading: "Contact", body: contact },
  ]},
  { slug: "acceptable-use", title: "Acceptable Use Policy", summary: "What you may not publish or do on Eventloom. It applies to hosts, guests and anyone else using the service.", sections: [
    { heading: "The basics", body: "Eventloom is for real events: parties, weddings, celebrations, meetups and similar gatherings. Use it honestly, lawfully and with respect for your guests. This policy is part of our Terms. We enforce it as described in our Content Reporting and Enforcement policy." },
    { heading: "Content that is not allowed", body: "- Illegal content, or content that promotes illegal activity.\n- Phishing, scams and fraud: fake events, fake fundraisers, fake ticket sales, or pages that ask for passwords, payment card or bank details, government ID numbers or similar information.\n- Impersonation: pretending to be another person, business, organization or Eventloom, or misleading people about who is behind an event.\n- Hate: attacking or dehumanizing people because of race, ethnicity, national origin, religion, caste, sex, gender identity, sexual orientation, disability, age or serious illness, or promoting hate groups.\n- Harassment: bullying, threats, intimidation, or publishing someone's private information (such as home address or phone number) without consent.\n- Sexual content: sexually explicit material or pornography, and offering sexual services.\n- Minors: any content that sexualizes or exploits children. We remove it, close the account and report it to the authorities, as the law requires. Don't publish more about children than the event needs.\n- Violence: threats, incitement, glorifying violence or terrorism, or promoting self-harm.\n- Illegal goods and services, such as illegal drugs, weapons or counterfeit goods, unlicensed gambling, or ticket fraud.\n- Content that infringes someone else's copyright, trademark, privacy or other rights.\n- Malware, malicious links, or anything that harms people's devices." },
    { heading: "Misusing guests' information", body: "- Using an RSVP form to harvest contact details for marketing lists, selling guest information, or making up an event to collect people's details.\n- Asking guests for information the event doesn't need, especially sensitive information such as government ID numbers, financial details, passwords or detailed health information. Meal and accessibility needs are fine.\n- Sending spam or unsolicited messages to guests' email addresses or phone numbers." },
    { heading: "Misusing the service", body: "- Getting around our rate limits, bot checks, moderation or payment, or using AI features to create content this policy prohibits.\n- Probing, scanning or testing our systems for weaknesses (see our Security page for responsible disclosure), overloading the service, or scraping other people's pages or data.\n- Accessing accounts, events or data that aren't yours.\n- Sending false or bad-faith reports." },
    { heading: "If you see a problem", body: `Use "Report this page" on the event page or email ${email}. If someone is in immediate danger, contact local emergency services first.` },
  ]},
  { slug: "reporting", title: "Content Reporting and Enforcement", summary: "How we check content, how to report a page, what we do about reports, and how to appeal.", sections: [
    { heading: "Automated checks", body: `We check event text and uploaded images with automated moderation tools (currently OpenAI's moderation service), for example when a photo is uploaded or a page is published. Content that is likely to break our Acceptable Use Policy may be blocked. Automated checks make mistakes; if you think your content was blocked wrongly, email ${email} and a person will review it.` },
    { heading: "Reporting a page", body: `Anyone can report an event page using the "Report this page" link on the page, or by emailing ${email} with the page link. We ask for the page address, the reason, any details that will help us understand the problem, and, if you want a reply, your email address. To prevent abuse of the reporting tool we store a keyed hash of your IP address with the report. We don't tell the host who reported them unless the law requires it. Copyright complaints follow our Copyright and Takedown policy, which works differently.` },
    { heading: "How we review reports", body: "A person reviews reports. We deal first with reports about child safety, credible threats, and phishing or fraud. We may look at the page, its history and related accounts, and we may contact the host." },
    { heading: "What we may do", body: "- Take no action, if the page doesn't break our rules.\n- Ask the host to change the page.\n- Remove specific content.\n- Suspend the page: it is taken offline for visitors and RSVPs close. The host can still sign in and see their dashboard.\n- Suspend or close the host's account, for serious or repeated breaches.\n- Preserve information and report to the police or other authorities when the law requires it or someone's safety is at risk.\n\nWe choose the action that fits how serious the problem is." },
    { heading: "Telling the host and appeals", body: `We normally tell the host what we did and why, unless the law prevents it or telling them would put someone at risk. A host can appeal within 30 days by emailing ${email} with "Appeal" in the subject and the page link. Someone who was not involved in the first decision will review the appeal where possible, and we aim to reply within 7 days. If we made a mistake we restore the page.` },
    { heading: "Refunds", body: "Pages suspended or removed because they broke our rules are not refunded. If a page was suspended by mistake we restore it, and we may extend its hosting period to make up for the time it was offline." },
  ]},
  { slug: "copyright", title: "Copyright and Takedown Policy", summary: "How rights holders can report copyright infringement on Eventloom pages, and how hosts can respond.", sections: [
    { heading: "Our approach", body: "Hosts must only use content they own or have permission to use. We respond to copyright notices under Canada's notice-and-notice system and, for content that is clearly infringing, we may also remove it or disable access to it, following a process similar to the US Digital Millennium Copyright Act (DMCA). For trademark or other rights complaints, contact us the same way." },
    { heading: "Sending a copyright notice", body: `Email ${email} with "Copyright notice" in the subject, or mail it to ${mailingAddress}. Include:\n\n- your name, postal address and email address (and, if you act for the owner, the owner's name);\n- the work you say is infringed, and the right you hold in it;\n- the exact Eventloom page link and where the material appears on the page;\n- how it infringes, and the date and time of the alleged infringement;\n- a statement that you believe in good faith the use is not authorized by the owner, its agent or the law;\n- a statement that the information in your notice is accurate and, under penalty of perjury, that you are the owner or authorized to act for the owner;\n- your physical or electronic signature.` },
    { heading: "What we do with a notice", body: "- We forward a notice that meets Canada's requirements to the host and let you know we did, or why we couldn't.\n- We keep records that identify the host for the time Canadian law requires (six months, or one year if you tell us you have started court proceedings).\n- If the material is clearly infringing and your notice is complete, we may also remove it or disable access to it and tell the host.\n- We don't charge for handling notices." },
    { heading: "Counter-notice for hosts", body: `If your content was removed and you believe that was a mistake, or that you have permission, send a counter-notice to ${email} with: your name, address, phone number and email; the content that was removed and where it appeared; a statement, under penalty of perjury, that you believe in good faith it was removed by mistake or misidentification; your consent to the jurisdiction of the courts where the complainant can sue you; your agreement to accept legal papers from the complainant; and your signature. We forward it to the complainant and may restore the content after 10 to 14 business days unless they tell us they have started a court action.` },
    { heading: "Repeat infringers and false claims", body: "We close the accounts of hosts who repeatedly infringe. Knowingly false notices or counter-notices can make the sender legally liable for the harm caused." },
  ]},
  { slug: "cookies", title: "Cookie and Tracking Notice", summary: "Eventloom uses only the cookies and browser storage it needs to work. No analytics or advertising tracking.", sections: [
    { heading: "What we use", body: "- Sign-in cookies: when you sign in, our authentication provider (Supabase) sets cookies (their names start with \"sb-\") that keep you signed in. They are removed when you sign out or the session ends.\n- Bot checks: forms that need protection from spam (sign-up, RSVPs, privacy requests and reports) use Cloudflare Turnstile. It runs a check in your browser and processes your IP address and browser signals to tell people from bots. We use it only for security.\n- Browser storage: while you build a page we keep its progress in your browser's local storage so a refresh doesn't lose it. It stays on your device.\n- Hosting: our hosting provider (Vercel) may use technical signals to route traffic and protect against attacks." },
    { heading: "What we don't use", body: "We don't use analytics, advertising cookies, tracking pixels, social media trackers or cross-site tracking. Fonts are served from our own domain, so pages don't load anything from Google." },
    { heading: "Consent and your choices", body: "These cookies and storage are strictly necessary for Eventloom to work and stay secure, so we don't show a consent banner. If we ever add analytics or anything non-essential, we will update this notice first and ask for your consent where the law requires it. You can block or delete cookies in your browser settings, but you won't be able to sign in without sign-in cookies." },
  ]},
  { slug: "subprocessors", title: "Subprocessors and International Transfers", summary: "The service providers that process personal information for Eventloom, what they do and where.", sections: [
    { heading: "Current providers", body: "- Supabase: sign-in, database and photo storage. Processes host accounts, event content, photos, guest replies and all other records. United States.\n- Vercel: hosting, content delivery and running the application. Processes every request, including IP addresses and page content in transit. United States, with servers worldwide.\n- OpenAI: AI page generation and editing, and automated moderation of event text and uploaded images. Processes host instructions, page text and photos sent for generation or moderation, not guest replies. United States.\n- Stripe: payment processing. Processes the payer's card and billing details and email address; we receive payment status and reference numbers. United States and worldwide.\n- Cloudflare (Turnstile): bot checks on forms. Processes IP address and browser signals during a check. Worldwide.\n- ImprovMX: forwards email sent to our @eventloom.co addresses to our inbox. Processes the messages you send us and their sender addresses." },
    { heading: "Other services", body: "Google Fonts: we use fonts from Google Fonts, but they are bundled and served from our own domain, so visitors' browsers don't contact Google. Our servers fetch font files from Google when generating share-preview images; no personal information is sent.\n\nNot in use: we do not currently use error-monitoring, analytics, advertising or domain-registration providers. We will list any we add here first." },
    { heading: "Transfers and changes", body: "Eventloom is based in Canada and these providers process information outside Canada, mainly in the United States. We rely on each provider's data processing terms and transfer safeguards, such as standard contractual clauses. When we add or replace a provider we will update this page and its version number." },
  ]},
  { slug: "dpa", title: "Creator Data Processing Addendum", summary: "Eventloom's commitments to hosts about guest RSVP data it processes on their behalf.", sections: [
    { heading: "Scope and roles", body: "This addendum is part of the Terms and covers personal information in guest RSVP replies. The host decides what to collect and why and is responsible for it (the controller). Eventloom processes it on the host's behalf (the processor or service provider)." },
    { heading: "What Eventloom will do", body: `- Process guest replies only to provide the host's event page, RSVP collection, dashboard, export and deletion, or as the law requires.\n- Limit access to people who need it to run or support the service, and keep the information confidential.\n- Protect it with the safeguards in our Privacy Policy and Security page.\n- Use only the providers listed on our Subprocessors page, under contracts that protect the information, and list new ones there before we use them. If you object to a change you can stop using Eventloom and delete your data.\n- Help hosts answer guests' requests to access, correct or delete their information.\n- Tell affected hosts without undue delay after we confirm a breach involving their guests' information, with the details we have.\n- Delete guest replies automatically ${RSVP_RETENTION_DAYS_AFTER_EVENT} days after the event ends, or sooner when the host deletes them, the event or the account. Hosts can export replies as a CSV file before then.\n- Give hosts reasonable information they need to show compliance, on request.` },
    { heading: "What the host will do", body: "Give guests a clear privacy notice (the event privacy notice is required before publishing), collect only what the event needs, have a lawful basis for collecting it, and handle exported replies securely." },
    { heading: "Liability", body: "Each party's liability under this addendum is subject to the limits in the Terms, except where the law doesn't allow those limits." },
  ]},
  { slug: "domains", title: "Domain Registration, Renewal, and Transfer Policy", summary: "Custom-domain purchase is not currently offered. This policy applies only if and when it is.", sections: [
    { heading: "Not currently offered", body: "Eventloom does not currently sell or register custom domains, and no domain charges apply. Every published page uses an Eventloom address. The rest of this policy describes how domain registration would work, and applies only if and when we offer it. We will update this policy and the Refund and Cancellation Policy before anyone can buy a domain." },
    { heading: "Ownership", body: "You would be the registrant and owner of any domain bought through Eventloom. You must give accurate registrant information and complete any verification the registry requires. Eventloom would not claim ownership of your domain." },
    { heading: "Renewal and expiry", body: "Automatic renewal would be off. Renewal prices would be shown separately. If a domain is not renewed, it can stop working and may be lost." },
    { heading: "Security and transfers", body: "Changes to contact details, renewals, unlocking and transfer codes would require multi-factor authentication. You could transfer your domain away once registry and ICANN transfer locks have expired." },
  ]},
  { slug: "accessibility", title: "Accessibility Statement", summary: "Eventloom aims to meet WCAG 2.2 Level AA for hosts and guests.", sections: [
    { heading: "Our commitment", body: "We want hosts and guests to be able to use Eventloom with a keyboard, screen reader, zoom or other assistive technology, and we aim to meet the Web Content Accessibility Guidelines (WCAG) 2.2 at Level AA. We test with automated tools and by hand." },
    { heading: "Event pages", body: "Event pages are designed by hosts, partly with AI. We check text colour contrast and let hosts describe their photos for people who can't see them, but a host's choices can still affect how accessible a page is. Hosts: please describe your photos and check that your page reads clearly." },
    { heading: "Get help or report a barrier", body: `If something on Eventloom is hard to use, or you need information in a different format, email ${email} with the page link and how you would like us to respond. We aim to reply within 5 business days.` },
  ]},
  { slug: "security", title: "Security and Responsible Disclosure", summary: "How Eventloom protects the service, and how to report a security problem.", sections: [
    { heading: "How we protect Eventloom", body: "We keep each host's data separate with access controls, require multi-factor authentication for sensitive actions, use HTTPS and encrypted storage, hash IP addresses, keep logging to a minimum, rate-limit public forms, check payment notifications are genuinely from Stripe, scan our dependencies for known vulnerabilities, and review changes before they reach production." },
    { heading: "Report a vulnerability", body: `Email ${email} with "Security" in the subject. Include the affected page or link, steps to reproduce, the impact, and how to contact you. We will acknowledge your report within 5 business days and keep you updated.` },
    { heading: "Rules for research", body: "Only test against your own account and events. Don't access, change or delete other people's data, don't degrade the service (no denial-of-service or heavy automated scanning), don't use social engineering or phishing, and don't publicly disclose an issue until we have fixed it or 90 days have passed, whichever is first. If you follow these rules and act in good faith, we will not pursue legal action against you for your research. We don't currently offer paid bug bounties." },
  ]},
];

export function legalDocument(slug: string) { return legalDocuments.find((document) => document.slug === slug); }

/** The exact text hashed into legal_documents.content_sha256 for LEGAL_VERSION. */
export function legalDocumentCanonicalText(document: LegalDocument, version: string = LEGAL_VERSION) {
  return [
    `${document.slug}@${version}`,
    document.title,
    document.summary,
    ...document.sections.map((section) => `## ${section.heading}\n${section.body}`),
  ].join("\n\n");
}

export type LegalBlock = { kind: "paragraph"; text: string } | { kind: "list"; items: string[] };

export function legalSectionBlocks(body: string): LegalBlock[] {
  return body.split(/\n{2,}/).map((chunk) => {
    const lines = chunk.split("\n");
    return lines.every((line) => line.startsWith("- "))
      ? { kind: "list" as const, items: lines.map((line) => line.slice(2)) }
      : { kind: "paragraph" as const, text: chunk };
  });
}
