import type { EventScheduleItem, RsvpField } from "@/lib/types";

// Keep in step with MOOD_PALETTES in src/lib/event-theme.ts: the build reads these words from a brief to pick a palette.
export type OccasionMood = "blush" | "navy" | "gold" | "lavender" | "forest" | "sunset";

export type OccasionTemplateContent = {
  slug: string;
  /** Short display name, e.g. "Baby shower". */
  name: string;
  title: string;
  metaDescription: string;
  heading: string;
  intro: string;
  cardBlurb: string;
  /** Prefix for the build brief ("Baby shower event. …"), same as the landing composer's event type label. */
  eventTypeLabel: string;
  /** Starting brief for "Use this template". Must not name a palette; the chosen style adds one. */
  brief: string;
  include: readonly { title: string; body: string }[];
  schedule: readonly EventScheduleItem[];
  scheduleNote: string;
  rsvpQuestions: readonly { question: string; why: string; field?: RsvpField }[];
  wording: readonly { tip: string; example?: string }[];
  faqs: readonly { question: string; answer: string }[];
  related: readonly string[];
  landingPages: readonly string[];
  sample: {
    title: string;
    subtitle: string;
    date: string;
    venueName: string;
    venueAddress: string;
    rsvpFields: readonly RsvpField[];
  };
  styles: readonly { mood: OccasionMood; name: string; prompt: string }[];
};

export const occasionTemplateContent: readonly OccasionTemplateContent[] = [
  {
    slug: "wedding",
    name: "Wedding",
    title: "Wedding Website Template with RSVP",
    metaDescription: "A wedding website template with schedule, venue, travel notes, and an RSVP that collects meal choices. See a live sample, then make it yours.",
    heading: "A wedding website template guests can rely on.",
    intro: "Most wedding questions arrive by text in the last two weeks: what time, where to park, is there a dress code, can I bring someone. A good wedding website answers them once, and the RSVP tells you who is coming and what they will eat.",
    cardBlurb: "Ceremony, reception, travel, and meal choices on one page.",
    eventTypeLabel: "Wedding",
    brief: "A wedding website with our names, the ceremony and reception schedule, venue and parking details, a dress code note, travel and hotel information for out-of-town guests, and an RSVP that asks for attendance, guest names, and meal choices.",
    include: [
      { title: "Names, date, and city", body: "Put them at the very top. Guests open the link to confirm the basics, so they should not have to scroll for the date or the town you are getting married in." },
      { title: "Ceremony and reception locations", body: "If they are in different places, list both with full addresses and say how long the drive is between them. Mention parking, shuttles, or the closest rideshare drop-off." },
      { title: "Timeline", body: "Give the ceremony start time and ask guests to arrive 20 to 30 minutes earlier. Add cocktail hour, dinner, and the last dance so people can plan childcare and rides home." },
      { title: "Dress code and weather", body: "One sentence is enough: \"Garden formal. The ceremony is on grass, so skip stilettos.\" Mention if part of the day is outdoors and what happens if it rains." },
      { title: "Travel and accommodation", body: "List one or two hotels with a room block code and a booking deadline, plus the nearest airport. Out-of-town guests read this section more than any other." },
      { title: "Who is invited", body: "Be clear about plus-ones and children. Naming each invited guest in the RSVP avoids awkward conversations later." },
    ],
    schedule: [
      { time: "3:30 PM", title: "Guests arrive", description: "Seating opens in the orchard. Water and shade by the entrance." },
      { time: "4:00 PM", title: "Ceremony", location: "The orchard lawn", description: "About 25 minutes. Unplugged, so please keep phones away." },
      { time: "4:30 PM", title: "Cocktail hour", location: "Barn terrace", description: "Drinks, small plates, and lawn games while photos are taken." },
      { time: "6:00 PM", title: "Dinner and toasts", location: "The barn", description: "Seated dinner. Find your table on the board by the door." },
      { time: "8:00 PM", title: "Dancing", description: "Last song at 10:45 PM. Shuttles back to town leave at 11:00 PM." },
    ],
    scheduleNote: "Publish the guest-facing times, not the vendor run sheet. Guests need arrival time, ceremony length, when food is served, and when it ends.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "The one answer you need from everyone, ideally by your caterer's final-count date.", field: "attendance" },
      { question: "Names of everyone in your party", why: "Lets you check replies against the invitation and build the seating chart.", field: "guest_names" },
      { question: "Meal choice for each guest", why: "Caterers usually need entrée counts two to three weeks out.", field: "meal_preference" },
      { question: "Dietary restrictions or allergies", why: "Ask separately from meal choice so a nut allergy is not lost inside \"chicken\".", field: "note" },
      { question: "Email for updates", why: "Useful if the weather plan or shuttle times change.", field: "email" },
    ],
    wording: [
      { tip: "Lead with the invitation, not the logistics. A warm first line sets the tone for the whole page.", example: "Together with their families, Maya Chen and Theo Alvarez invite you to celebrate their marriage." },
      { tip: "State the RSVP deadline as a date, not \"soon\". Pick a date about three weeks before the wedding.", example: "Kindly reply by May 15 so we can give our caterer final numbers." },
      { tip: "Handle plus-ones gently and in one place.", example: "We have reserved 2 seats in your honor." },
    ],
    faqs: [
      { question: "When should a wedding website go live?", answer: "Share it with save-the-dates, six to eight months before the wedding, or with invitations if you are not sending save-the-dates. Collect RSVPs until about three weeks before the day." },
      { question: "Can guests RSVP without creating an account?", answer: "Yes. Guests open your link, read the details, and reply. They never sign up for anything." },
      { question: "What does it cost to publish?", answer: "You can draft and refine the site first. Publishing costs $20 once and keeps the site live for a year." },
    ],
    related: ["engagement", "bridal-shower", "anniversary"],
    landingPages: ["wedding-rsvp-website", "rsvp-website", "private-event-website"],
    sample: {
      title: "Maya & Theo",
      subtitle: "We are getting married in the orchard where we met. Come for the ceremony, stay for dinner and dancing.",
      date: "Saturday, June 12, 2027 · 4:00 PM",
      venueName: "Hollow Creek Farm",
      venueAddress: "214 Orchard Road, Hudson Valley",
      rsvpFields: ["name", "attendance", "guest_names", "meal_preference", "note"],
    },
    styles: [
      { mood: "blush", name: "Garden romance", prompt: "romantic garden wedding, soft and intimate" },
      { mood: "navy", name: "Evening formal", prompt: "black-tie formal wedding, luxury evening" },
      { mood: "forest", name: "Woodland", prompt: "relaxed woodland wedding with a casual, friendly feel" },
    ],
  },
  {
    slug: "engagement",
    name: "Engagement party",
    title: "Engagement Party Website Template",
    metaDescription: "An engagement party website template with the party details, a short story of how you met, and an RSVP. Preview a live sample and start your own.",
    heading: "An engagement party website that sets the tone.",
    intro: "An engagement party is often the first time both families and friend groups meet. The website is where you set expectations: how formal it is, whether gifts are expected, and that the wedding date is still to come.",
    cardBlurb: "The party details, your story, and who is hosting.",
    eventTypeLabel: "Engagement",
    brief: "An engagement party website with our names, who is hosting, the date, time, and address, a short story of how we met and got engaged, a dress code, a note that gifts are not expected, and an RSVP for attendance and party size.",
    include: [
      { title: "Who is hosting", body: "Engagement parties are often thrown by parents or friends. Saying who is hosting tells guests whose home they are going to and who to contact." },
      { title: "The proposal story", body: "Two or three sentences about how you met and how the question was asked. It gives guests something to talk about with people they have not met." },
      { title: "Time, place, and format", body: "Say whether it is a seated dinner, a cocktail party, or a backyard afternoon, and roughly how long it will run." },
      { title: "Gift guidance", body: "Many guests are unsure whether to bring a gift. A short line removes the guesswork either way." },
      { title: "What comes next", body: "If you know the wedding season or city, mention it. If not, say that details will follow so guests do not ask all evening." },
    ],
    schedule: [
      { time: "6:30 PM", title: "Welcome drinks", location: "Garden patio", description: "Sparkling wine and something non-alcoholic on arrival." },
      { time: "7:15 PM", title: "A few words", description: "Short toasts from both families. Ten minutes, we promise." },
      { time: "7:30 PM", title: "Dinner stations", description: "Food is served buffet style through the evening." },
      { time: "9:30 PM", title: "Dessert and goodbyes", description: "Cake, coffee, and a photo with the two of us on the way out." },
    ],
    scheduleNote: "Keep it loose. Engagement parties work best with a clear start time, one moment for toasts, and an honest end time.",
    rsvpQuestions: [
      { question: "Will you join us?", why: "The essential count for food and drinks.", field: "attendance" },
      { question: "How many in your party?", why: "Engagement invitations are often extended to couples and families, so party size matters.", field: "party_size" },
      { question: "Names of your guests", why: "Helps the hosts make introductions between the two families.", field: "guest_names" },
      { question: "Anything we should know?", why: "Dietary needs, accessibility, or a note for the couple.", field: "note" },
    ],
    wording: [
      { tip: "Name the hosts on the invitation line when someone else is throwing the party.", example: "Please join Linda and Raj Patel in celebrating the engagement of Priya and Sam." },
      { tip: "Be direct about gifts. Guests appreciate it.", example: "Your company is the only gift we need." },
      { tip: "Keep the tone a step less formal than your wedding will be." },
    ],
    faqs: [
      { question: "Who should be invited to an engagement party?", answer: "Traditionally, only people who will also be invited to the wedding. If the party is bigger than the wedding guest list, say so on the website to avoid hurt feelings later." },
      { question: "Can I reuse the site for the wedding?", answer: "Each published event is its own site. Many couples start with the engagement party and create a separate wedding site later, when the details are set." },
      { question: "How far ahead should we send the link?", answer: "Four to six weeks before the party is plenty. Ask for replies one week before so the hosts can finalize food." },
    ],
    related: ["wedding", "bridal-shower", "anniversary"],
    landingPages: ["event-website-builder", "rsvp-website", "online-rsvp"],
    sample: {
      title: "Priya & Sam",
      subtitle: "He asked on a rainy Tuesday and she said yes before he finished. Come celebrate with both of our families.",
      date: "Friday, September 17, 2027 · 6:30 PM",
      venueName: "The Patel Home",
      venueAddress: "48 Linden Avenue, Oak Park",
      rsvpFields: ["name", "attendance", "party_size", "guest_names", "note"],
    },
    styles: [
      { mood: "gold", name: "Champagne", prompt: "elegant formal engagement dinner, luxury details" },
      { mood: "blush", name: "Romantic", prompt: "romantic intimate engagement party in the garden" },
      { mood: "sunset", name: "Backyard", prompt: "casual relaxed backyard engagement party" },
    ],
  },
  {
    slug: "birthday",
    name: "Birthday party",
    title: "Birthday Party Website Template with RSVP",
    metaDescription: "A birthday party website template with time, place, what to bring, and an RSVP with party size. See a live sample birthday page and make your own.",
    heading: "A birthday party page friends will actually read.",
    intro: "Birthday invitations get lost in group chats. One page with the time, address, and an RSVP button gives everyone a single place to check, and gives you a real headcount instead of a row of thumbs-up emoji.",
    cardBlurb: "Time, place, what to bring, and a real headcount.",
    eventTypeLabel: "Birthday",
    brief: "A birthday party website with the name and age being celebrated, the date, start and end time, the address with parking notes, what to wear or bring, whether it is a surprise, and an RSVP for attendance and party size.",
    include: [
      { title: "Whose birthday, and which one", body: "A name and a number make the page feel personal. Leave the age out if the guest of honor would rather you did." },
      { title: "Start and end time", body: "An end time helps parents plan pickups and lets adults know whether it is a dinner or an all-night affair." },
      { title: "Exact address and how to get in", body: "Apartment buzzer codes, which door to use, and where to park save you from answering the phone while hosting." },
      { title: "Theme or dress code", body: "If there is a costume theme or an outdoor activity, say so clearly so nobody shows up underdressed for bowling or overdressed for a hike." },
      { title: "Surprise instructions", body: "For surprise parties, give an arrival time 20 to 30 minutes before the guest of honor, and a reminder not to post about it." },
      { title: "Gifts", body: "\"No gifts, please\" or a single idea is enough. Skip it entirely if gifts are not a concern." },
    ],
    schedule: [
      { time: "7:00 PM", title: "Doors open", description: "Drinks and snacks on the rooftop. Buzz apartment 4B." },
      { time: "8:00 PM", title: "Dinner", description: "Tacos from the place around the corner. Vegetarian options included." },
      { time: "9:00 PM", title: "Cake", description: "Candles, singing, and the obligatory speech." },
      { time: "9:30 PM", title: "Music and games", description: "Stay as late as you like. Quiet hours start at midnight." },
    ],
    scheduleNote: "For kids' parties, keep the schedule to arrival, activity, food, cake, and pickup. For adults, one anchor moment like cake is enough.",
    rsvpQuestions: [
      { question: "Can you make it?", why: "Your headcount for food and space.", field: "attendance" },
      { question: "How many are coming?", why: "Partners and kids add up quickly at birthday parties.", field: "party_size" },
      { question: "Phone number", why: "Handy for last-minute changes on the day, or for coordinating a surprise.", field: "phone" },
      { question: "Allergies or food preferences", why: "Especially important when children are invited.", field: "note" },
    ],
    wording: [
      { tip: "Match the tone of the guest of honor. A 30th can be cheeky; a grandparent's 90th should feel warm.", example: "Jordan is turning 30 and would like to pretend it is still 2015. Join us." },
      { tip: "For kids' parties, address the parents and say clearly whether siblings are welcome.", example: "Siblings are welcome. Please let us know how many are coming so we have enough cupcakes." },
      { tip: "For a surprise, put the warning at the top in plain words.", example: "Shh. This is a surprise. Please arrive by 6:45 PM." },
    ],
    faqs: [
      { question: "How early should I send a birthday invitation?", answer: "Two to three weeks ahead for most parties, four to six weeks for a milestone birthday where guests may travel. Ask for replies a few days before you need to order food." },
      { question: "Do my friends need an app to RSVP?", answer: "No. They open the link in any browser and reply. No account and no download." },
      { question: "Can I change the details after sending the link?", answer: "Yes. Edit the page whenever plans change. Everyone sees the latest version at the same link." },
    ],
    related: ["graduation", "quinceanera", "retirement"],
    landingPages: ["birthday-event-website", "online-rsvp", "rsvp-website"],
    sample: {
      title: "Jordan Turns 30",
      subtitle: "Rooftop tacos, a questionable playlist, and the people who made the last decade worth it.",
      date: "Saturday, March 6, 2027 · 7:00 PM",
      venueName: "Jordan's Rooftop",
      venueAddress: "312 Mercer Street, Apartment 4B",
      rsvpFields: ["name", "attendance", "party_size", "phone", "note"],
    },
    styles: [
      { mood: "sunset", name: "Bright and bold", prompt: "playful bold birthday party, loud and graphic" },
      { mood: "lavender", name: "Dreamy", prompt: "playful dreamy birthday with round soft shapes" },
      { mood: "navy", name: "Night out", prompt: "late dinner, sharp modern lines" },
    ],
  },
  {
    slug: "baby-shower",
    name: "Baby shower",
    title: "Baby Shower Website Template with RSVP",
    metaDescription: "A baby shower website template with the host, date, registry note, and an RSVP. Preview a real sample baby shower page and start yours in a minute.",
    heading: "A baby shower page that makes planning gentle.",
    intro: "A baby shower usually has several organizers and a guest list that spans generations. A simple page keeps the details consistent for everyone, from the parents' college friends to the great-aunt who prefers to call.",
    cardBlurb: "Hosts, registry, timing, and a calm RSVP.",
    eventTypeLabel: "Baby shower",
    brief: "A baby shower website with the parent or parents' names, who is hosting, the date and time, the address, a note about the registry, any games or activities, and an RSVP for attendance, party size, and dietary needs.",
    include: [
      { title: "Who it is for, and who is hosting", body: "Name the parent or parents and the hosts. Guests often need to contact a host rather than the expecting parent." },
      { title: "Registry information", body: "Mention where the registry lives and whether you prefer books instead of cards, secondhand items, or no gifts at all." },
      { title: "Format and length", body: "Brunch, afternoon tea, or a co-ed backyard barbecue each call for different outfits and expectations. Say which it is." },
      { title: "Accessibility", body: "Note stairs, seating, and parking. Showers often include older relatives and guests who are pregnant themselves." },
      { title: "Virtual option", body: "If you will stream part of the shower or open gifts on a call, add the link or say it will be shared before the day." },
    ],
    schedule: [
      { time: "11:00 AM", title: "Brunch is served", description: "Quiche, fruit, and plenty of coffee. Mimosas with and without the bubbles." },
      { time: "11:45 AM", title: "A couple of games", description: "Nothing embarrassing. Prizes for the winners." },
      { time: "12:30 PM", title: "Gifts", description: "Opened together. Feel free to grab more food." },
      { time: "1:30 PM", title: "Wrap up", description: "Take a cupcake home." },
    ],
    scheduleNote: "Two to three hours is the sweet spot. Put the gift opening near the end so guests who need to leave early can.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Your count for food and seating.", field: "attendance" },
      { question: "How many in your party?", why: "Useful when the shower is co-ed or children are welcome.", field: "party_size" },
      { question: "Dietary needs", why: "Brunch menus are easy to adapt if you know in advance.", field: "note" },
      { question: "Email address", why: "So the hosts can send a thank-you note or a change of plan.", field: "email" },
    ],
    wording: [
      { tip: "Name the hosts first if someone else is throwing the shower.", example: "Hosted by Ana and Beth, with love for Clara." },
      { tip: "Mention the registry gently and once.", example: "Clara is registered online, though a children's book with a note inside means just as much." },
      { tip: "If the baby's sex or name is still a secret, keep the theme neutral and do not mention it." },
    ],
    faqs: [
      { question: "When should a baby shower be held?", answer: "Most showers are held four to eight weeks before the due date. Send the link about four weeks before the shower." },
      { question: "Can several hosts work on the same page?", answer: "One person creates the page and sees the replies. Co-hosts can send the creator changes to make, and every guest sees the update at the same link." },
      { question: "Do guests need an account to reply?", answer: "No. Guests reply from the link in any browser." },
      { question: "Are baby showers only for a first baby?", answer: "No. Many families hold a smaller sprinkle for a second or third baby, focused on diapers and essentials rather than a full registry. The same page works with a shorter guest list." },
    ],
    related: ["bridal-shower", "birthday", "reunion"],
    landingPages: ["rsvp-website", "private-event-website", "online-rsvp"],
    sample: {
      title: "A Shower for Clara",
      subtitle: "Baby Rivera arrives in April. Join us for brunch, a few gentle games, and a lot of tiny socks.",
      date: "Sunday, February 21, 2027 · 11:00 AM",
      venueName: "The Greenhouse Room",
      venueAddress: "90 Willow Street, Upper Montclair",
      rsvpFields: ["name", "attendance", "party_size", "email", "note"],
    },
    styles: [
      { mood: "blush", name: "Soft blush", prompt: "intimate brunch, soft and friendly" },
      { mood: "forest", name: "Garden", prompt: "garden brunch, editorial magazine feel" },
      { mood: "lavender", name: "Dreamy", prompt: "playful dreamy afternoon with round shapes" },
    ],
  },
  {
    slug: "bridal-shower",
    name: "Bridal shower",
    title: "Bridal Shower Website Template with RSVP",
    metaDescription: "A bridal shower website template with hosts, theme, registry, and RSVP. See a live sample bridal shower page, then create your own in minutes.",
    heading: "A bridal shower website the whole party can share.",
    intro: "Bridal showers are planned by a group and attended by people who may not know each other. The website lets the hosts agree on one set of details and gives guests a clear answer on theme, gifts, and timing.",
    cardBlurb: "Hosts, theme, registry, and one clear schedule.",
    eventTypeLabel: "Bridal shower",
    brief: "A bridal shower website with the name of the person being celebrated, the hosts, the date, time, and address, the theme or dress code, a note about the wedding registry, and an RSVP for attendance and dietary needs.",
    include: [
      { title: "The guest of honor and hosts", body: "Name who is being celebrated and the people hosting. Guests will want to know who to ask about gifts or directions." },
      { title: "Theme", body: "Tea party, garden brunch, or a cooking class: the theme affects what people wear and bring, so describe it in a sentence." },
      { title: "Registry and gift notes", body: "Point to the wedding registry and mention any shower-specific twist, like bringing a favorite recipe on a card." },
      { title: "Who is invited", body: "Shower guest lists are usually smaller than the wedding. Say whether it is women only, co-ed, or family and close friends." },
      { title: "Timing", body: "Most showers last two to three hours. A clear end time helps guests who are traveling." },
      { title: "Surprise or not", body: "Some showers are a surprise for the bride. If so, say it at the top, give an arrival time before she gets there, and ask guests not to mention it on social media." },
    ],
    schedule: [
      { time: "1:00 PM", title: "Arrive and mingle", description: "Lemonade, tea, and introductions." },
      { time: "1:30 PM", title: "Lunch", location: "Main tea room", description: "Finger sandwiches, salads, and scones." },
      { time: "2:15 PM", title: "Recipe swap and gifts", description: "Bring your favorite recipe on the card in your invitation." },
      { time: "3:30 PM", title: "Farewell", description: "Leave with a jar of homemade jam." },
    ],
    scheduleNote: "Showers feel relaxed when there is one shared activity. Build the schedule around it and keep the rest open.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Tea rooms and restaurants need firm counts.", field: "attendance" },
      { question: "Dietary restrictions", why: "Set menus can usually adapt with a week's notice.", field: "meal_preference" },
      { question: "A note for the bride", why: "Guests who cannot attend often want to send a message.", field: "note" },
      { question: "Email address", why: "For the recipe card reminder or a change of venue.", field: "email" },
    ],
    wording: [
      { tip: "Lead with the honoree, then the hosts.", example: "A bridal shower honoring Elena Brooks, hosted by her bridesmaids." },
      { tip: "Ask for activity contributions plainly.", example: "Please bring one recipe you love, written on the enclosed card." },
      { tip: "Keep registry links to the gift section, not the opening line." },
    ],
    faqs: [
      { question: "When should the bridal shower be?", answer: "Usually two to three months before the wedding. Send the link four to six weeks before the shower." },
      { question: "Should everyone at the shower be invited to the wedding?", answer: "Yes, by tradition. Inviting someone to a shower but not the wedding can feel like a request for a gift." },
      { question: "How much does a shower website cost?", answer: "You can draft it first. Publishing costs $20 once for a year, which covers the page and the RSVPs." },
      { question: "What is a good bridal shower theme?", answer: "Pick something that suits the bride rather than a trend: a tea party for a baker, a garden brunch for a plant lover, a cooking class for someone who loves to host. Let the theme shape one activity and the dress code, not every detail." },
    ],
    related: ["wedding", "engagement", "baby-shower"],
    landingPages: ["rsvp-website", "wedding-rsvp-website", "online-rsvp"],
    sample: {
      title: "Showering Elena",
      subtitle: "Tea, too many scones, and a recipe swap for the best cook we know. Before she says I do, we say cheers.",
      date: "Saturday, April 10, 2027 · 1:00 PM",
      venueName: "Primrose Tea Room",
      venueAddress: "15 Market Square, Old Town",
      rsvpFields: ["name", "attendance", "email", "meal_preference", "note"],
    },
    styles: [
      { mood: "blush", name: "Tea party", prompt: "romantic tea party, paper and linen details" },
      { mood: "gold", name: "Vintage", prompt: "vintage old-world brunch with editorial type" },
      { mood: "lavender", name: "Lavender", prompt: "intimate garden afternoon, soft lavender" },
    ],
  },
  {
    slug: "graduation",
    name: "Graduation party",
    title: "Graduation Party Website Template with RSVP",
    metaDescription: "A graduation party website template with ceremony and party times, open house hours, and an RSVP. See a live sample and create your own page.",
    heading: "A graduation party page for the open house crowd.",
    intro: "Graduation season means overlapping parties, relatives in town for one weekend, and guests who drop in for an hour. A website that separates the ceremony from the party, and says when to come and go, saves everyone a lot of guessing.",
    cardBlurb: "Ceremony, open house hours, and drop-in friendly RSVPs.",
    eventTypeLabel: "Graduation party",
    brief: "A graduation party website with the graduate's name, school, and degree or class year, the party date and open house hours, the address and parking, whether the ceremony is open to guests, and an RSVP for attendance and party size.",
    include: [
      { title: "The graduate and the achievement", body: "Name, school, and class year or degree. A line about what comes next (college, a first job, a gap year) gives guests a conversation starter." },
      { title: "Ceremony versus party", body: "Make it clear whether guests are invited to the ceremony or only the party. Ceremony tickets are often limited." },
      { title: "Open house hours", body: "Many graduation parties are come-and-go. Give a window, like 2 to 6 PM, so guests can visit several parties in one day." },
      { title: "Parking and directions", body: "Graduation weekend means crowded streets. Point to overflow parking or suggest carpooling." },
      { title: "Cards and gifts", body: "Say whether there will be a card box, or that a note of advice for the graduate is welcome." },
    ],
    schedule: [
      { time: "10:00 AM", title: "Commencement", location: "Westfield High School stadium", description: "Ticketed. Family only, as seating is limited." },
      { time: "2:00 PM", title: "Open house begins", description: "Come whenever you can. Food is out all afternoon." },
      { time: "4:00 PM", title: "A few words", description: "A short toast to the graduate in the backyard." },
      { time: "6:00 PM", title: "Open house ends", description: "Thank you for celebrating with us." },
    ],
    scheduleNote: "For open houses, the important times are the window and the one moment you want everyone present for, like a toast.",
    rsvpQuestions: [
      { question: "Will you stop by?", why: "Even a rough count helps you order enough food.", field: "attendance" },
      { question: "How many are coming?", why: "Families with younger kids often come together.", field: "party_size" },
      { question: "Advice for the graduate", why: "Guests love leaving a note, and the graduate gets a keepsake.", field: "note" },
    ],
    wording: [
      { tip: "Celebrate the person, not only the diploma.", example: "Four years, two jobs, one very proud family. Join us in celebrating Ava." },
      { tip: "Make drop-in hours explicit so guests do not worry about arriving late.", example: "Stop by any time between 2 and 6 PM." },
      { tip: "If the ceremony is ticketed, say so up front to avoid awkward asks." },
      { tip: "Thank guests who traveled.", example: "To everyone who drove in from Ohio: thank you. The guest room is ready." },
    ],
    faqs: [
      { question: "When should I send graduation party invitations?", answer: "Three to four weeks before the party. In busy graduation weekends, earlier is better so guests can plan around other parties." },
      { question: "Can guests RSVP if they are only dropping by?", answer: "Yes. A quick yes and party size takes under a minute and needs no account." },
      { question: "Can I add photos of the graduate?", answer: "Yes. You can upload photos when you start your event, then refine the page in plain language." },
      { question: "Should we host a joint graduation party?", answer: "Joint parties with friends from the same class are common and save money. List every graduate's name on the page, agree on costs in advance, and make the open house window longer so guests can spend time with each family." },
    ],
    related: ["birthday", "retirement", "reunion"],
    landingPages: ["event-website-builder", "online-rsvp", "rsvp-website"],
    sample: {
      title: "Congratulations, Ava",
      subtitle: "Westfield High, Class of 2027, and off to study marine biology this fall. Come celebrate before she heads for the coast.",
      date: "Saturday, June 5, 2027 · 2:00 to 6:00 PM",
      venueName: "The Okafor Backyard",
      venueAddress: "77 Birch Lane, Westfield",
      rsvpFields: ["name", "attendance", "party_size", "note"],
    },
    styles: [
      { mood: "navy", name: "School colors", prompt: "bold graphic graduation party, sharp" },
      { mood: "sunset", name: "Summer", prompt: "summer street festival, loud and casual" },
      { mood: "forest", name: "Classic", prompt: "classic editorial celebration with a friendly feel" },
    ],
  },
  {
    slug: "anniversary",
    name: "Anniversary party",
    title: "Anniversary Party Website Template with RSVP",
    metaDescription: "An anniversary party website template for milestone celebrations, with the couple's story, schedule, and RSVP. Preview a sample and create yours.",
    heading: "An anniversary website that tells the story so far.",
    intro: "Milestone anniversaries bring together people from every chapter of a couple's life, often organized by their children. The page is a place for the details and for a little of the history that makes the celebration meaningful.",
    cardBlurb: "A milestone, a little history, and a clear RSVP.",
    eventTypeLabel: "Anniversary",
    brief: "An anniversary party website with the couple's names and which anniversary it is, who is hosting, the date, time, and venue, a short history of the couple, whether it is a surprise, a note about gifts, and an RSVP for attendance and party size.",
    include: [
      { title: "The milestone", body: "Twenty-fifth, fortieth, fiftieth: say which anniversary and the year they married. It frames the whole event." },
      { title: "A short history", body: "Where they met, the wedding, the places they have lived. A few lines works better than a long biography." },
      { title: "Hosts", body: "Anniversary parties are often thrown by children or close friends. Name them so guests know who to contact." },
      { title: "Gift guidance", body: "Many couples prefer no gifts. A popular alternative is asking guests to bring a favorite memory or photo." },
      { title: "Surprise or not", body: "If it is a surprise, say so clearly and give an arrival time before the couple arrives." },
      { title: "Photos through the years", body: "Ask family for old photos ahead of time and mention that a slideshow or photo table is planned. Guests often bring their own prints once they know." },
    ],
    schedule: [
      { time: "5:00 PM", title: "Arrival and drinks", location: "The terrace", description: "Look for the table of wedding photos from 1977." },
      { time: "6:00 PM", title: "Dinner", location: "Main dining room", description: "Family-style Italian, just like their wedding." },
      { time: "7:30 PM", title: "Toasts and memories", description: "Children, grandchildren, and one or two old friends." },
      { time: "8:15 PM", title: "First dance, again", description: "Followed by cake and coffee." },
    ],
    scheduleNote: "Include a moment that echoes the wedding, like the first dance song or the same cake. Guests remember it.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Restaurants need numbers for a private room.", field: "attendance" },
      { question: "Who is coming with you?", why: "Grown children often bring their own families.", field: "guest_names" },
      { question: "A favorite memory of the couple", why: "Collected replies make a lovely keepsake book.", field: "note" },
    ],
    wording: [
      { tip: "Write from the hosts if the children are throwing the party.", example: "Please join us in celebrating fifty years of Rosa and Daniel." },
      { tip: "Mention gifts once, kindly.", example: "Your presence is the gift. If you would like, bring a photo or a memory to share." },
      { tip: "For a surprise, put the arrival time in bold at the top." },
    ],
    faqs: [
      { question: "Which anniversaries are usually celebrated with a party?", answer: "The 25th, 40th, 50th, and 60th are the most common, but any anniversary that feels meaningful is worth celebrating." },
      { question: "Can relatives who are not online reply?", answer: "Most relatives can open a link on a phone or tablet, and there is no account to create. For anyone who would rather call, the hosts can take their reply by phone." },
      { question: "What does publishing cost?", answer: "Drafting comes first. Publishing costs $20 once for a year, with no subscription." },
      { question: "Should an anniversary party be a surprise?", answer: "Only if the couple enjoys surprises. For most milestone anniversaries, telling the couple lets them invite old friends you might not know about and enjoy the anticipation." },
    ],
    related: ["wedding", "retirement", "reunion"],
    landingPages: ["private-event-website", "rsvp-website", "event-website-builder"],
    sample: {
      title: "Rosa & Daniel",
      subtitle: "Fifty years, three children, seven grandchildren, and the same Sunday crossword. Join us for dinner in their honor.",
      date: "Saturday, October 9, 2027 · 5:00 PM",
      venueName: "Trattoria Bellini",
      venueAddress: "220 Harbor Street, private dining room",
      rsvpFields: ["name", "attendance", "guest_names", "note"],
    },
    styles: [
      { mood: "gold", name: "Golden", prompt: "elegant formal dinner, luxury details" },
      { mood: "blush", name: "Romantic", prompt: "romantic intimate dinner, paper details" },
      { mood: "navy", name: "Classic", prompt: "vintage evening with editorial type" },
    ],
  },
  {
    slug: "quinceanera",
    name: "Quinceañera",
    title: "Quinceañera Website Template with RSVP",
    metaDescription: "A quinceañera website template with Mass and reception details, the court, padrinos, and an RSVP. See a live sample quince page and start your own.",
    heading: "A quinceañera website for the whole family.",
    intro: "A quinceañera often has two parts, a Mass or blessing and a reception, plus a court, padrinos, and relatives traveling in from far away. The website keeps all of it in one place, and can be written in English, Spanish, or both.",
    cardBlurb: "Mass, reception, court, and padrinos in one place.",
    eventTypeLabel: "Quinceañera",
    brief: "A quinceañera website with the quinceañera's name, the Mass or blessing and reception times and locations, the court and padrinos, a dress code, travel notes for family coming from out of town, and an RSVP for attendance and guest names. Include Spanish and English text.",
    include: [
      { title: "Mass and reception", body: "List both with times and addresses. If guests are only invited to the reception, make that clear." },
      { title: "The court and padrinos", body: "Naming the damas, chambelanes, and padrinos honors them and helps guests know who is who on the day." },
      { title: "Language", body: "Write the page in the languages your guests speak. A bilingual page makes grandparents and school friends equally comfortable." },
      { title: "Dress code", body: "Receptions range from semi-formal to black tie. One line saves a lot of questions." },
      { title: "Travel", body: "Relatives often travel for a quince. Add nearby hotels and the closest airport." },
      { title: "Traditions and gifts", body: "Explain any traditions guests can take part in, such as the last doll or the money dance, and whether gifts are expected. Friends who have never attended a quince will appreciate the guidance." },
    ],
    schedule: [
      { time: "2:00 PM", title: "Misa de acción de gracias", location: "St. Anthony Parish", description: "Thanksgiving Mass with family and the court." },
      { time: "6:00 PM", title: "Reception doors open", location: "Salón Las Palmas", description: "Find your table on the seating board." },
      { time: "7:00 PM", title: "Grand entrance and waltz", description: "Sofía and her court, followed by the father-daughter dance." },
      { time: "8:00 PM", title: "Dinner", description: "Served family style." },
      { time: "9:00 PM", title: "Surprise dance and party", description: "Dancing until midnight." },
    ],
    scheduleNote: "Give the entrance and waltz a fixed time. It is the moment every relative wants to see.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Halls and caterers need final numbers early.", field: "attendance" },
      { question: "Names of everyone attending", why: "Seating charts for quinces are often large and detailed.", field: "guest_names" },
      { question: "Meal preference", why: "Useful if you are offering more than one entrée.", field: "meal_preference" },
      { question: "Phone number", why: "Relatives often prefer a call for updates.", field: "phone" },
    ],
    wording: [
      { tip: "Open with the family's invitation.", example: "With the blessing of God and the love of her family, Sofía Ramírez invites you to celebrate her quince años." },
      { tip: "Write both languages side by side rather than two separate pages, so everyone sees the same details." },
      { tip: "Thank the padrinos by name. It is a meaningful gesture in the community." },
    ],
    faqs: [
      { question: "Can my quinceañera website be in Spanish?", answer: "Yes. Describe your event in Spanish, or ask for both languages, and you can review and edit every word before you publish." },
      { question: "How early should we share the link?", answer: "Two to three months ahead, especially when family is traveling. Ask for replies four weeks before the date." },
      { question: "Do guests need an account to reply?", answer: "No. Guests reply from the link on any phone or computer." },
      { question: "When should a quinceañera be held?", answer: "Close to the fifteenth birthday, often on the nearest Saturday. Many families book the church and hall nine to twelve months ahead, so share the date early even if the details come later." },
    ],
    related: ["birthday", "bar-bat-mitzvah", "graduation"],
    landingPages: ["birthday-event-website", "event-website-builder", "rsvp-website"],
    sample: {
      title: "Mis XV Años, Sofía",
      subtitle: "Join our family for Mass, dinner, and a night of dancing as Sofía turns fifteen. Acompáñanos.",
      date: "Saturday, August 14, 2027 · 2:00 PM",
      venueName: "Salón Las Palmas",
      venueAddress: "1450 Alameda Boulevard, San Antonio",
      rsvpFields: ["name", "attendance", "guest_names", "meal_preference", "phone"],
    },
    styles: [
      { mood: "lavender", name: "Princess", prompt: "elegant formal celebration, luxury details" },
      { mood: "gold", name: "Gold and ivory", prompt: "elegant black-tie evening, gold details" },
      { mood: "blush", name: "Rose", prompt: "romantic celebration with paper details" },
    ],
  },
  {
    slug: "bar-bat-mitzvah",
    name: "Bar or bat mitzvah",
    title: "Bar and Bat Mitzvah Website Template",
    metaDescription: "A bar or bat mitzvah website template with service and party details, kiddush, travel notes, and an RSVP. Preview a live sample and start yours.",
    heading: "A bar or bat mitzvah website for the service and the party.",
    intro: "A b'nai mitzvah weekend can include a Shabbat service, a kiddush lunch, an evening party with a separate kids' room, and guests traveling in. A clear page helps guests who have never been to one feel prepared.",
    cardBlurb: "Service, kiddush, party, and travel in one place.",
    eventTypeLabel: "Bar mitzvah",
    brief: "A bar or bat mitzvah website with the child's name and Hebrew name, the service time and synagogue address, the kiddush or lunch, the evening party details, dress code notes for the service and the party, hotel information, and an RSVP for attendance, guest names, and meal choices.",
    include: [
      { title: "Service details", body: "The synagogue name, address, and start time. Note that services often start before the bar or bat mitzvah portion and that guests are welcome to arrive at the start." },
      { title: "What to expect", body: "A short note for guests unfamiliar with the service: how long it runs, head coverings, and whether phones should be off on Shabbat." },
      { title: "Party information", body: "Evening parties often have a different venue, dress code, and a separate space for kids. Spell each out." },
      { title: "Kids and teens", body: "Say whether younger siblings are invited and what time teens should be picked up." },
      { title: "Travel", body: "Many families travel in for the weekend. List a hotel within walking distance of the synagogue if guests observe Shabbat." },
    ],
    schedule: [
      { time: "9:30 AM", title: "Shabbat morning service", location: "Temple Beth Shalom", description: "Noah will be called to the Torah at about 10:45 AM." },
      { time: "12:30 PM", title: "Kiddush lunch", location: "Social hall", description: "Everyone at the service is welcome." },
      { time: "7:00 PM", title: "Evening party", location: "The Foundry", description: "Cocktail attire. Teen lounge with games and a DJ." },
      { time: "11:00 PM", title: "Party ends", description: "Teen pickup at the main entrance." },
    ],
    scheduleNote: "Give guests the time the honoree is expected to read, so relatives traveling with children can plan around it.",
    rsvpQuestions: [
      { question: "Will you join us?", why: "Separate counts for the service and the party help catering.", field: "attendance" },
      { question: "Names of everyone attending", why: "Seating and the kids' room need names, not just numbers.", field: "guest_names" },
      { question: "Meal choice", why: "Kosher caterers often need entrée counts in advance.", field: "meal_preference" },
      { question: "Which events you will attend", why: "Ask in the note: service, kiddush, party, or all three.", field: "note" },
    ],
    wording: [
      { tip: "Include the Hebrew name if the family wishes; it is a personal touch.", example: "Noah Benjamin Levi, Natan ben David v'Rachel, will be called to the Torah as a bar mitzvah." },
      { tip: "Write a short \"what to expect\" note for non-Jewish friends. It makes them feel welcome rather than unsure." },
      { tip: "Give teens their own clear line about the party.", example: "Teens: the lounge opens at 7:30 PM. Parents, pickup is at 11." },
    ],
    faqs: [
      { question: "How early should we share a bar or bat mitzvah website?", answer: "Six to eight weeks before, or with your printed invitations. Out-of-town guests appreciate hotel details even earlier." },
      { question: "Can the page cover both the service and the party?", answer: "Yes. Most families put both on one page with separate times, addresses, and dress codes." },
      { question: "Is there a monthly fee?", answer: "No. Publishing costs $20 once and keeps the site live for a year." },
      { question: "What should guests wear?", answer: "For the service, guests usually dress as they would for any religious service, and head coverings are often provided at the door. Evening parties set their own dress code, so state each one separately on the page." },
    ],
    related: ["quinceanera", "birthday", "graduation"],
    landingPages: ["event-website-builder", "private-event-website", "rsvp-website"],
    sample: {
      title: "Noah's Bar Mitzvah",
      subtitle: "Noah will be called to the Torah as a bar mitzvah. Join us for the service, lunch, and a party that night.",
      date: "Saturday, November 6, 2027 · 9:30 AM",
      venueName: "Temple Beth Shalom",
      venueAddress: "600 Maple Avenue, Short Hills",
      rsvpFields: ["name", "attendance", "guest_names", "meal_preference", "note"],
    },
    styles: [
      { mood: "navy", name: "Classic navy", prompt: "formal elegant celebration, luxury details" },
      { mood: "sunset", name: "Party night", prompt: "bold graphic party with loud color" },
      { mood: "gold", name: "Gold", prompt: "vintage editorial celebration" },
    ],
  },
  {
    slug: "retirement",
    name: "Retirement party",
    title: "Retirement Party Website Template with RSVP",
    metaDescription: "A retirement party website template with the career highlights, toasts, venue, and an RSVP. See a live sample retirement page and create yours.",
    heading: "A retirement party page that honors a career.",
    intro: "Retirement parties mix colleagues, former colleagues, family, and friends who have never met. The website explains the plan, gives people a place to send a message if they cannot come, and makes it easy to organize toasts.",
    cardBlurb: "Career highlights, toasts, and colleagues old and new.",
    eventTypeLabel: "Retirement party",
    brief: "A retirement party website with the retiree's name, their role and years of service, the date, time, and venue, the plan for toasts, a note about a group gift or card, and an RSVP for attendance and a message for the retiree.",
    include: [
      { title: "The career in a few lines", body: "Years of service, roles held, and one or two highlights. Former colleagues love being reminded of the shared history." },
      { title: "Who is organizing", body: "Name the organizer and how to reach them, especially if the party is outside work hours." },
      { title: "Toasts", body: "If you want people to speak, say so and ask them to let you know in their reply. It keeps speeches to a sensible number." },
      { title: "Group gift or card", body: "Explain how to contribute to a group gift or sign a card, or say that no gifts are expected." },
      { title: "Messages from afar", body: "Some people who worked with the retiree years ago will not be able to come. Invite them to leave a note." },
    ],
    schedule: [
      { time: "5:30 PM", title: "Drinks", location: "The Lantern Room", description: "First round is on the department." },
      { time: "6:15 PM", title: "Toasts", description: "Short speeches from colleagues past and present. Five minutes each, please." },
      { time: "7:00 PM", title: "Dinner", description: "Buffet with vegetarian and gluten-free options." },
      { time: "8:30 PM", title: "Send-off", description: "Card, gift, and one last group photo." },
    ],
    scheduleNote: "After-work parties should start 30 to 60 minutes after the workday ends so people can travel without rushing.",
    rsvpQuestions: [
      { question: "Will you be there?", why: "Restaurants and function rooms need numbers.", field: "attendance" },
      { question: "Email address", why: "For updates and to share photos afterwards.", field: "email" },
      { question: "A message for the retiree", why: "Collected messages make a keepsake, especially from people who cannot attend.", field: "note" },
      { question: "Would you like to say a few words?", why: "Ask in the note so you can plan the toasts.", field: "note" },
    ],
    wording: [
      { tip: "Make the honoree the subject, not the company.", example: "After 32 years of keeping the library running, Margaret is turning the page." },
      { tip: "Be explicit that former colleagues and family are welcome if they are." },
      { tip: "Keep the group gift note practical.", example: "We are collecting for a gift. Contributions go to Dev by May 1." },
    ],
    faqs: [
      { question: "Who should be invited to a retirement party?", answer: "Current and former colleagues, close friends, and family. Ask the retiree for a short list of people from earlier in their career." },
      { question: "Can people who cannot attend still leave a message?", answer: "Yes. They can reply that they cannot attend and leave a note, which the organizer sees with the other replies." },
      { question: "Can a workplace use Eventloom?", answer: "Yes. Any organizer can create the page. Publishing costs $20 for one event for a year." },
      { question: "When should a retirement party take place?", answer: "Within a couple of weeks of the last working day, while colleagues still see the retiree regularly. Send the link three to four weeks ahead, and earlier if former colleagues need to travel." },
    ],
    related: ["corporate-event", "anniversary", "birthday"],
    landingPages: ["event-website-builder", "online-rsvp", "rsvp-website"],
    sample: {
      title: "Cheers to Margaret",
      subtitle: "Thirty-two years at the Riverside Library, three renovations, and thousands of recommendations. Join us to celebrate her retirement.",
      date: "Thursday, May 20, 2027 · 5:30 PM",
      venueName: "The Lantern Room",
      venueAddress: "41 Riverside Drive, upstairs",
      rsvpFields: ["name", "attendance", "email", "note"],
    },
    styles: [
      { mood: "forest", name: "Library green", prompt: "literary editorial evening, friendly" },
      { mood: "navy", name: "Professional", prompt: "professional evening, sharp and modern" },
      { mood: "gold", name: "Golden years", prompt: "vintage celebration with editorial type" },
    ],
  },
  {
    slug: "reunion",
    name: "Reunion",
    title: "Reunion Website Template with RSVP",
    metaDescription: "A family or class reunion website template with the weekend schedule, lodging, costs, and an RSVP. See a live sample and create your own reunion page.",
    heading: "A reunion website that gets everyone in one place.",
    intro: "Reunions are planned by one or two volunteers for dozens of people who have scattered over the years. The website does the heavy lifting: what is happening, where to stay, what it costs, and who is coming.",
    cardBlurb: "Weekend plans, lodging, costs, and who is coming.",
    eventTypeLabel: "Reunion",
    brief: "A reunion website for a family or class reunion with the group name, the dates, the schedule of events, the main venue, lodging options, any cost per person, what to bring, and an RSVP for attendance, party size, and guest names.",
    include: [
      { title: "Who the reunion is for", body: "Family name, class year, or team. Make the scope clear: are spouses, kids, and extended family included?" },
      { title: "The full weekend", body: "Reunions often span a Friday mixer, a main event, and a Sunday brunch. List each with a time and location." },
      { title: "Lodging", body: "A recommended hotel or campground, with a booking deadline if you have a block of rooms." },
      { title: "Costs", body: "If there is a per-person fee for food or the venue, say how much and how to pay. Transparency avoids awkward conversations later." },
      { title: "What to bring", body: "Old photos, a dish for the potluck, or a family recipe. Small asks make people feel part of it." },
    ],
    schedule: [
      { time: "Friday 7:00 PM", title: "Welcome night", location: "Lakeside pavilion", description: "Name tags, pizza, and catching up." },
      { time: "Saturday 11:00 AM", title: "Family picnic", location: "Pine Lake Park", description: "Games for kids, the annual softball match, and a group photo at 3 PM." },
      { time: "Saturday 6:00 PM", title: "Dinner", location: "Lakeside pavilion", description: "Catered barbecue. Bring a dessert to share." },
      { time: "Sunday 10:00 AM", title: "Farewell brunch", description: "Pancakes and goodbyes until next time." },
    ],
    scheduleNote: "Schedule the group photo for a fixed time and say so twice. It is the hardest thing to organize on the day.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Lets you book enough food and space.", field: "attendance" },
      { question: "How many in your group?", why: "Families vary widely in size at reunions.", field: "party_size" },
      { question: "Names of everyone coming", why: "For name tags and to see which branches of the family will be there.", field: "guest_names" },
      { question: "Which events you will join", why: "Ask in the note so you can plan each meal.", field: "note" },
      { question: "Email address", why: "To share photos and the date of the next reunion.", field: "email" },
    ],
    wording: [
      { tip: "Lead with the reason to come, not the logistics.", example: "It has been ten years. The kids are taller, the stories are better. Come home to Pine Lake." },
      { tip: "State costs plainly with a pay-by date.", example: "Dinner is $25 per adult, kids under 12 free. Please pay Aunt June by July 1." },
      { tip: "Ask people to forward the link to relatives you may have missed." },
    ],
    faqs: [
      { question: "How far ahead should a reunion be announced?", answer: "Six to twelve months for family reunions that involve travel, three to six months for local class reunions. Ask for replies six weeks before." },
      { question: "Can relatives forward the link?", answer: "Yes. Anyone with the link can view the page and reply, so it is easy to reach branches of the family you do not have contact details for." },
      { question: "Can the page show a weekend of events?", answer: "Yes. The schedule can list several events across multiple days, each with its own time and location." },
    ],
    related: ["anniversary", "graduation", "holiday-party"],
    landingPages: ["event-website-builder", "rsvp-website", "online-rsvp"],
    sample: {
      title: "The Okonkwo Family Reunion",
      subtitle: "Three generations, one lake, and a long weekend together. Come home to Pine Lake.",
      date: "July 23 to 25, 2027",
      venueName: "Pine Lake Park",
      venueAddress: "Lakeside pavilion, 9 Shore Road",
      rsvpFields: ["name", "attendance", "party_size", "guest_names", "email", "note"],
    },
    styles: [
      { mood: "forest", name: "Lakeside", prompt: "relaxed outdoor weekend, friendly and casual" },
      { mood: "sunset", name: "Summer", prompt: "bold graphic summer festival feel" },
      { mood: "navy", name: "Classic", prompt: "vintage class reunion, editorial" },
    ],
  },
  {
    slug: "corporate-event",
    name: "Corporate event",
    title: "Corporate Event Website Template with RSVP",
    metaDescription: "A corporate event website template for offsites, launches, and client evenings, with agenda, venue, and RSVP. See a live sample and build yours.",
    heading: "A corporate event page that looks as good as your brand.",
    intro: "Offsites, client dinners, and product launches need a page that looks professional, gives the agenda at a glance, and collects RSVPs with the details your team needs for badges, catering, and follow-up.",
    cardBlurb: "Agenda, venue, and RSVPs for offsites and launches.",
    eventTypeLabel: "Corporate event",
    brief: "A corporate event website with the event name and host company, the date, the agenda with session times, the venue address and access instructions, the dress code, and an RSVP for attendance, email, and dietary needs.",
    include: [
      { title: "What and why", body: "A one-sentence purpose. \"An evening to thank our customers\" sets a different expectation than \"a product briefing.\"" },
      { title: "Agenda", body: "Times for arrival, sessions, breaks, and the end. Attendees plan travel and calls around it." },
      { title: "Venue access", body: "Building entrance, security check-in, badge pickup, and parking or transit. Office buildings are confusing for visitors." },
      { title: "Dress code", body: "Business casual and \"come as you are\" mean different things to different people. Add an example." },
      { title: "Contact", body: "Someone attendees can email with questions. It reduces no-shows when plans change." },
      { title: "Accessibility", body: "Ask about accessibility needs and say whether the venue has step-free access, quiet spaces, or captions for presentations. Corporate guests rarely mention this unless invited to." },
    ],
    schedule: [
      { time: "5:30 PM", title: "Check-in", location: "Lobby, 12th floor", description: "Bring photo ID for building security." },
      { time: "6:00 PM", title: "Product walkthrough", description: "A 20-minute look at what we shipped this year." },
      { time: "6:30 PM", title: "Customer panel", description: "Three teams on how they use it every day." },
      { time: "7:15 PM", title: "Reception", location: "Terrace", description: "Food, drinks, and time with the team." },
      { time: "9:00 PM", title: "Close", description: "Thanks for coming." },
    ],
    scheduleNote: "Put the end time on the page. Busy guests are more likely to say yes when they know how long they are committing to.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Venue capacity and catering.", field: "attendance" },
      { question: "Work email", why: "For the calendar invite, building access lists, and follow-up.", field: "email" },
      { question: "Dietary requirements", why: "Caterers need them a week ahead.", field: "meal_preference" },
      { question: "Company and role", why: "Ask in the note to plan seating and introductions.", field: "note" },
    ],
    wording: [
      { tip: "Lead with value for the guest, not the company.", example: "An evening with the people building the tools you use every day." },
      { tip: "Write the agenda in plain language, without internal project names." },
      { tip: "Give a firm RSVP date tied to a real reason.", example: "Please reply by March 3 so we can register you with building security." },
      { tip: "If space is limited, say so and explain what happens next.", example: "Space is limited to 60 guests. We will confirm your place by email." },
    ],
    faqs: [
      { question: "Can we match our brand colors?", answer: "Yes. Describe your colors or paste hex codes when you start, then adjust the design in plain language." },
      { question: "Do attendees need an account to RSVP?", answer: "No. Attendees reply from the link, which keeps sign-up friction away from busy guests." },
      { question: "How is pricing handled for a company?", answer: "Each published event costs $20 once for a year." },
      { question: "Can we send the link to external guests?", answer: "Yes. Clients, partners, and candidates open the same link as your team. They see only the event page, never your other events or the list of replies." },
    ],
    related: ["holiday-party", "retirement", "reunion"],
    landingPages: ["event-website-builder", "online-rsvp", "private-event-website"],
    sample: {
      title: "Northwind Customer Evening",
      subtitle: "A look at what we shipped this year, a panel with three customers, and a reception on the terrace.",
      date: "Thursday, March 11, 2027 · 5:30 PM",
      venueName: "Northwind Offices",
      venueAddress: "500 Market Street, 12th floor",
      rsvpFields: ["name", "attendance", "email", "meal_preference", "note"],
    },
    styles: [
      { mood: "navy", name: "Corporate", prompt: "corporate professional conference, sharp" },
      { mood: "sunset", name: "Launch", prompt: "startup tech launch, modern and bold" },
      { mood: "forest", name: "Offsite", prompt: "relaxed professional offsite, friendly" },
    ],
  },
  {
    slug: "holiday-party",
    name: "Holiday party",
    title: "Holiday Party Website Template with RSVP",
    metaDescription: "A holiday party website template for office or family gatherings, with time, place, gift exchange rules, and an RSVP. Preview a sample and start yours.",
    heading: "A holiday party page with every detail sorted.",
    intro: "December calendars fill fast. A holiday party page with a clear date, a gift exchange rule, and an RSVP deadline helps you get on people's calendars early and know how much food to buy.",
    cardBlurb: "Date, dress code, gift exchange rules, and a headcount.",
    eventTypeLabel: "Holiday party",
    brief: "A holiday party website with the host's name, the date, time, and address, the dress code or theme, the gift exchange rules and spending limit, what to bring, and an RSVP for attendance, party size, and dietary needs.",
    include: [
      { title: "Date and time, early", body: "Send the link three to four weeks ahead. Holiday weekends fill quickly and people plan travel early." },
      { title: "Theme or dress code", body: "Ugly sweater, cocktail attire, or pajamas. A theme gives guests something to look forward to." },
      { title: "Gift exchange rules", body: "Spending limit, type of exchange (Secret Santa, white elephant), and whether it is optional." },
      { title: "Potluck or catered", body: "If guests should bring something, suggest categories so you do not end up with six desserts." },
      { title: "Kids and plus-ones", body: "Office parties and family gatherings have different norms. State yours." },
      { title: "Food notes", body: "Say what will be served and flag common allergens. Holiday food is rich, and guests with restrictions appreciate knowing whether to eat beforehand." },
    ],
    schedule: [
      { time: "7:00 PM", title: "Mulled cider and snacks", description: "Sweater judging starts as soon as you walk in." },
      { time: "8:00 PM", title: "Dinner", description: "Potluck. Last names A to M bring a side, N to Z bring a dessert." },
      { time: "9:00 PM", title: "White elephant", description: "$25 limit. Wrapped, unlabeled, and slightly ridiculous." },
      { time: "10:30 PM", title: "Last call", description: "Cider to go." },
    ],
    scheduleNote: "Put the gift exchange after dinner, when everyone has arrived. Late guests miss the fun if it happens first.",
    rsvpQuestions: [
      { question: "Can you come?", why: "Food, chairs, and gift exchange numbers.", field: "attendance" },
      { question: "How many are you bringing?", why: "Partners and kids change the plan quickly.", field: "party_size" },
      { question: "What will you bring?", why: "Ask in the note to balance the potluck.", field: "note" },
    ],
    wording: [
      { tip: "Make the gift rules unmissable.", example: "White elephant: $25 limit, wrapped, no labels." },
      { tip: "Keep the language inclusive if your guests celebrate different holidays.", example: "Join us for an end-of-year party before everyone scatters for the holidays." },
      { tip: "Mention transport if drinks are served.", example: "The 10 bus stops at the corner until 1 AM." },
      { tip: "Give the RSVP date a reason.", example: "Reply by December 1 so we can draw names for Secret Santa." },
    ],
    faqs: [
      { question: "When should holiday party invitations go out?", answer: "Three to four weeks ahead for December parties. For office parties, six weeks gives teams time to plan around travel." },
      { question: "Can I use it for an office party?", answer: "Yes. The same page works for a team gathering, a family dinner, or a neighborhood party." },
      { question: "What does it cost?", answer: "Draft first, then publish for $20 once. The site stays live for a year." },
      { question: "How do I run a fair gift exchange?", answer: "Set a spending limit, ask for gifts wrapped without labels, and decide the rules before the party: how many times a gift can be stolen and whether the last person can swap. Post the rules on the page so nobody argues at 10 PM." },
    ],
    related: ["corporate-event", "reunion", "birthday"],
    landingPages: ["online-rsvp", "rsvp-website", "event-website-builder"],
    sample: {
      title: "The Ugly Sweater Party",
      subtitle: "Mulled cider, a potluck, and a white elephant exchange that always gets out of hand. Wear your worst sweater.",
      date: "Saturday, December 11, 2027 · 7:00 PM",
      venueName: "The Nguyen House",
      venueAddress: "28 Chestnut Court",
      rsvpFields: ["name", "attendance", "party_size", "note"],
    },
    styles: [
      { mood: "forest", name: "Evergreen", prompt: "cozy relaxed party, paper details" },
      { mood: "navy", name: "Winter night", prompt: "elegant formal evening party, luxury" },
      { mood: "sunset", name: "Festive", prompt: "loud festival party, bold and graphic" },
    ],
  },
  {
    slug: "memorial",
    name: "Memorial service",
    title: "Memorial Service Website Template",
    metaDescription: "A memorial service website template with service details, an obituary, ways to honor them, and an RSVP. A calm page you can share with family and friends.",
    heading: "A memorial page to share the details with care.",
    intro: "When someone dies, families spend days answering the same questions by phone. A simple memorial page shares the service time and place, a few words about the person, and how to help, so the family can focus on each other.",
    cardBlurb: "Service details, a life remembered, and how to help.",
    eventTypeLabel: "Memorial",
    brief: "A memorial service website with the person's full name and dates, a short obituary, the service and reception times and locations, livestream information if there is one, how to send flowers or donate in their memory, and an RSVP for attendance and party size with a place to share a memory.",
    include: [
      { title: "Name and dates", body: "Full name, including a nickname or maiden name people may know, and birth and death years." },
      { title: "A short obituary", body: "Where they lived, what they loved, and the people they leave behind. A paragraph or two is enough." },
      { title: "Service and reception", body: "Times, addresses, and whether the reception is open to all. Note if the burial is private." },
      { title: "Livestream", body: "If some people cannot travel, add the stream link or say it will be posted before the service." },
      { title: "Flowers and donations", body: "Say whether the family prefers flowers or a donation to a named charity." },
      { title: "Practical help", body: "Families often need meals, rides from the airport, or someone to watch children during the service. A short note on how to help turns kind intentions into useful ones." },
    ],
    schedule: [
      { time: "11:00 AM", title: "Service", location: "Riverside Chapel", description: "Readings and remembrances from family and friends." },
      { time: "12:00 PM", title: "Committal", description: "Private, for immediate family." },
      { time: "1:00 PM", title: "Reception", location: "The church hall", description: "Lunch and time to share stories. All are welcome." },
    ],
    scheduleNote: "Keep it simple. Guests mainly need the service time, the reception time, and whether each is open to everyone.",
    rsvpQuestions: [
      { question: "Will you attend?", why: "Helps the family plan the reception.", field: "attendance" },
      { question: "How many in your party?", why: "Seating and food for the reception.", field: "party_size" },
      { question: "Share a memory", why: "Many families read these together afterwards. Make it optional.", field: "note" },
    ],
    wording: [
      { tip: "Use plain, gentle language. There is no need for formal phrasing.", example: "Please join us to remember Walter, and to share the stories he loved to tell." },
      { tip: "Be clear and kind about what is private.", example: "The burial will be private. Everyone is welcome at the reception." },
      { tip: "Name the charity in full if you ask for donations, so people can find it." },
    ],
    faqs: [
      { question: "Is it appropriate to ask for RSVPs for a memorial?", answer: "Yes, especially when there is a reception. Keep the request gentle and make it clear that guests are welcome even if they do not reply." },
      { question: "Can the page stay private?", answer: "Share the link only with the people you choose. Eventloom guest pages ask search engines not to index them, and replies are visible only to the event creator." },
      { question: "How long does the page stay online?", answer: "A published page stays live for a year, which leaves time to share photos and thank-you notes after the service." },
      { question: "What if the service date is not set yet?", answer: "Share the person's name, a short obituary, and how to send condolences now, and say that service details will follow. Update the page when plans are set, and everyone will see them at the same link." },
    ],
    related: ["anniversary", "reunion", "retirement"],
    landingPages: ["private-event-website", "rsvp-website", "event-website-builder"],
    sample: {
      title: "Remembering Walter Hayes",
      subtitle: "1941 to 2027. Teacher, gardener, and teller of long stories. Join us to celebrate his life.",
      date: "Saturday, May 8, 2027 · 11:00 AM",
      venueName: "Riverside Chapel",
      venueAddress: "3 Church Lane, Millbrook",
      rsvpFields: ["name", "attendance", "party_size", "note"],
    },
    styles: [
      { mood: "forest", name: "Quiet green", prompt: "quiet still editorial page, garden" },
      { mood: "navy", name: "Evening", prompt: "quiet still classic page, literary" },
      { mood: "lavender", name: "Soft", prompt: "quiet still intimate page, soft" },
    ],
  },
];
