-- Remove legacy email allowlists and anonymous RSVP policy from the quarantined
-- table. No role can access this table pending the retention review.
drop policy if exists "Admins can delete RSVPs" on private.rsvps;
drop policy if exists "Admins can update RSVPs" on private.rsvps;
drop policy if exists "Anyone can submit an RSVP" on private.rsvps;
drop policy if exists "Only admins can view RSVPs" on private.rsvps;

alter table private.rsvp_rate_limits add column if not exists id bigint generated by default as identity;
do $$ begin
  if not exists (select 1 from pg_constraint where conrelid = 'private.rsvp_rate_limits'::regclass and contype = 'p') then
    alter table private.rsvp_rate_limits add constraint rsvp_rate_limits_id_pkey primary key (id);
  end if;
end $$;

-- Cache auth.uid() once per statement and scope browser policies explicitly to
-- authenticated users.
drop policy if exists "Profiles are self-readable" on public.profiles;
create policy "Profiles are self-readable" on public.profiles for select to authenticated using (id = (select auth.uid()));
drop policy if exists "Profiles are self-updatable" on public.profiles;
create policy "Profiles are self-updatable" on public.profiles for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check (id = (select auth.uid()));

drop policy if exists "Members can read events" on public.events;
create policy "Members can read events" on public.events for select to authenticated using (owner_id = (select auth.uid()) or private.is_event_member(id));
drop policy if exists "Authenticated users can create events" on public.events;
create policy "Authenticated users can create events" on public.events for insert to authenticated with check (owner_id = (select auth.uid()));
drop policy if exists "Owners can update events" on public.events;
create policy "Owners can update events" on public.events for update to authenticated using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));

drop policy if exists "Users can read their AI credit account" on public.ai_credit_accounts;
create policy "Users can read their AI credit account" on public.ai_credit_accounts for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists "Users can read their AI credit ledger" on public.ai_credit_ledger;
create policy "Users can read their AI credit ledger" on public.ai_credit_ledger for select to authenticated using (user_id = (select auth.uid()));
drop policy if exists "Users can read their own platform admin flag" on public.platform_admins;
create policy "Users can read their own platform admin flag" on public.platform_admins for select to authenticated using (user_id = (select auth.uid()));

-- Add covering indexes for every current single/multi-column foreign key that
-- lacks one. Names derive from stable constraint names and remain idempotent.
do $$
declare row record;
begin
  for row in
    select n.nspname schema_name, c.relname table_name, con.conname constraint_name,
      array_agg(a.attname order by k.ordinality) column_names
    from pg_constraint con
    join pg_class c on c.oid = con.conrelid
    join pg_namespace n on n.oid = c.relnamespace
    join unnest(con.conkey) with ordinality k(attnum, ordinality) on true
    join pg_attribute a on a.attrelid = c.oid and a.attnum = k.attnum
    where con.contype = 'f' and n.nspname = 'public'
      and not exists (
        select 1 from pg_index i
        where i.indrelid = c.oid
          and (i.indkey::smallint[])[0:cardinality(con.conkey)-1] = con.conkey
      )
    group by n.nspname, c.relname, con.conname
  loop
    execute format('create index if not exists %I on %I.%I (%s)',
      left(row.constraint_name || '_idx', 63), row.schema_name, row.table_name,
      (select string_agg(format('%I', value), ', ') from unnest(row.column_names) value));
  end loop;
end $$;
